# This file was generated by GoReleaser. DO NOT EDIT.
cask "devsh" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "dc8862802d9b71dc78f1bcdf8599622338f9c24b148b31a1d6e4f03526e07162"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3fca273a40e394de62c9da2b31fd42bf0fe31ecb97688fa0b1f0f57db971e347"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c061f875d2e85f1ce29a24db02ac467eb11228e5a67de8319ed0bccccd9ff59e"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f6c2f3f1555754b7df18f1ab01284b6064b80e516f17b0651048c9d63bf55267"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Linux_arm64.tar.gz"
    end
  end

  name "devsh"
  desc "Shell that runs inside a development container"
  homepage "https://github.com/kukushkin/devsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devsh"

  # No zap stanza required

end
