# This file was generated by GoReleaser. DO NOT EDIT.
cask "devsh" do
  version "0.5.5"

  on_macos do
    on_intel do
      sha256 "61cc9fb59ee09dff31478d8dc0daaa7fa8047d1e9006ef67cd10a1f88d4d954f"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bba19f56118e0789a8ad39f67a62474ab5228ee32236858617d5a37e4cf7c03e"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e02b90e0d00a10c804bce627e62d0eaac54435b75620fa8c19b3acefa1f22aa"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "52ce49ece35db3eb830113d29a16e81786bb7405dfcb0b17ffe0c25f367092df"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Linux_arm64.tar.gz"
    end
  end

  name "devsh"
  desc "Shell that runs inside a development container"
  homepage "https://github.com/kukushkin/devsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devsh"

  # No zap stanza required

end
