# This file was generated by GoReleaser. DO NOT EDIT.
cask "devsh" do
  version "0.5.6"

  on_macos do
    on_intel do
      sha256 "7d0cace6d4f4e0a0ba1afc15b5201ce013b1a98ef0d593e5412236adbb4a471c"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "88214d11f0a1e705ffdb39007450e43f185552ad3af43db0f010adeca3902b25"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "958af434c88835f8b966871355f0d60223b0035d8a428a367a24dc3b81514feb"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a00a3e8f617b522a25c875636daf0f9502c8a5358eaca0f907ede5a15251a4ef"
      url "https://github.com/kukushkin/devsh/releases/download/v#{version}/devsh_Linux_arm64.tar.gz"
    end
  end

  name "devsh"
  desc "Shell that runs inside a development container"
  homepage "https://github.com/kukushkin/devsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devsh"

  # No zap stanza required

end
